### ISSUE TITLE
Canonical fork/version of this gem

### ISSUE THREAD

**Issue by jeremiahleeh** [maxlapshin/mysql2postgres#75]
Having trouble figuring out which fork of this gem to use. Is there a recommended canonical repo?

When I inspect the gemspec after `gem install mysqltopostgres` it looks like [ajokela's](https://github.com/ajokela/mysqltopostgres) fork is the source.

The repo here (maxlapshin) is much more active and it appears that an updated version is available here (0.2.20) that is not available at ajokela's fork (0.2.15).

**Comment by maxlapshin** [comment]
Right now this fork is supported

**Comment by nruth** [comment]
It's a bit confusing that this isn't the one on rubygems, in particular since [heroku points to rubygems](https://devcenter.heroku.com/articles/heroku-mysql) and that points to @ajokela rather than this repo. It'd be great if that ownership issue could be resolved. Otherwise the rubygems admins might change the owner if asked, since this is the source.

**Comment by paazmaya** [comment]
Seems that the Heroku article has been updated to point in this repository.
